name: fiam-llm-alpha
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.26
  - pandas>=2.2
  - polars>=1.7
  - pyarrow>=16
  - scikit-learn>=1.5
  - lightgbm>=4.4
  - xgboost>=2.1
  - pytorch>=2.3
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - transformers>=4.44
  - datasets>=2.20
  - tokenizers>=0.19
  - spacy>=3.7
  - nltk>=3.9
  - dvc>=3.50
  - git-lfs
  - mlflow>=2.16
  - hydra-core>=1.3
  - statsmodels>=0.14
  - matplotlib
  - seaborn
  - ruff>=0.6
  - black>=24.8
  - mypy>=1.11
  - pre-commit>=3.8
  - pytest>=8.3
  - pytest-cov>=5.0
  - pip:
      - sentencepiece
